name: Deploy Action

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache/restore dependencies
      uses: actions/cache@v1
      id: cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      
    - name: Publish to Github pages
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        GITHUB_EMAIL: ${{ secrets.DEPLOY_GITHUB_EMAIL }}
        GITHUB_USER: ${{ secrets.DEPLOY_GITHUB_USER }}
      run: |
        git config --global user.email "$GITHUB_EMAIL"
        git config --global user.name "$GITHUB_USER"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/Maskedman99/learningredux.git
        yarn deploy -u "github-actions-bot <support+actions@github.com>"
